### YamlMime:PowershellCmdlet
summary: |-
  Gets the current configuration of the nodes.
module: PSDesiredStateConfiguration
notes: ""
links:
- text: Windows PowerShell Desired State Configuration Overview
  href: /powershell/scripting/dsc/overview/dscforengineers
- text: Get-DscConfigurationStatus
  href: Get-DscConfigurationStatus.yml
- text: Restore-DscConfiguration
  href: Restore-DscConfiguration.yml
- text: Start-DscConfiguration
  href: Start-DscConfiguration.yml
- text: Test-DscConfiguration
  href: Test-DscConfiguration.yml
syntaxes:
- Get-DscConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [<CommonParameters>]
examples:
- title: 'Example 1: Get the configuration for the local computer'
  code: |-
    PS C:\> Get-DscConfiguration
  description: |-
    This command gets the current state for the local computer.
  summary: ""
- title: 'Example 2: Get the configuration for a specified computer'
  code: |-
    PS C:\> $Session = New-CimSession -ComputerName "Server01" -Credential ACCOUNTS\PattiFuller
    PS C:\> Get-DscConfiguration -CimSession $Session
  description: |-
    This example gets the current state from a computer specified by a CIM session.
    The example creates a CIM session for a computer named Server01 for use with the cmdlet.
    Alternatively, create an array of CIM sessions to apply the cmdlet to multiple specified computers.

    The first command creates a CIM session by using the **New-CimSession** cmdlet, and then stores the **CimSession** object in the **$Session** variable.
    The command prompts you for a password.
    For more information, type `Get-Help New-CimSession`.

    The second command gets the current configuration for the computers identified by the **CimSession** objects stored in the **$Session** variable, in this case, the computer named Server01.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Indicates that this cmdlet runs the command as a background job.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Management.Infrastructure.CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](/powershell/module/cimcmdlets/new-cimsession) or [Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: PSDesiredStateConfiguration.Get-DscConfiguration
name: Get-DscConfiguration
description: |-
  The **Get-DscConfiguration** cmdlet gets the current configuration of the nodes, if the configuration exists.
  Specify computers by using Common Information Model (CIM) sessions.
  If you do not specify a target computer, the cmdlet gets the configuration from the local computer.
metadata:
  external help file: Get-DSCConfiguration.cdxml-help.xml
  keywords: powershell,cmdlet
  Locale: en-US
  Module Name: PSDesiredStateConfiguration
  ms.date: 06/09/2017
  online version: https://docs.microsoft.com/powershell/module/psdesiredstateconfiguration/get-dscconfiguration?view=powershell-5.1&WT.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-DscConfiguration
