### YamlMime:PowershellCmdlet
summary: |-
  Reapplies the previous configuration for the node.
module: PSDesiredStateConfiguration
notes: ""
links:
- text: Windows PowerShell Desired State Configuration Overview
  href: /powershell/scripting/dsc/overview/dscforengineers
- text: Get-DscConfiguration
  href: Get-DscConfiguration.yml
- text: Get-DscConfigurationStatus
  href: Get-DscConfigurationStatus.yml
- text: Start-DscConfiguration
  href: Start-DscConfiguration.yml
- text: Test-DscConfiguration
  href: Test-DscConfiguration.yml
syntaxes:
- >-
  Restore-DscConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Restore the configuration for the local computer'
  code: |-
    PS C:\> Restore-DscConfiguration
  description: |-
    This command restores the configuration for the local computer.
  summary: ""
- title: 'Example 2: Restore configuration for a specified computer'
  code: |-
    PS C:\> $Session = New-CimSession -ComputerName "Server01" -Credential ACCOUNTS\PattiFuller
    PS C:\> Restore-DscConfiguration -CimSession $Session
  description: |-
    This example restores configuration on a computer specified by a CIM session.
    The example creates a CIM session for a computer named Server01 for use with the cmdlet.
    Alternatively, create an array of CIM sessions to apply the cmdlet to multiple specified computers.

    The first command creates a CIM session by using the **New-CimSession** cmdlet, and then stores the **CimSession** object in the $Session variable.
    The command prompts you for a password.
    For more information, type `Get-Help New-CimSession`.

    The second command restores the configuration for the computers identified by the **CimSession** objects stored in the $Session variable, in this case, the computer named Server01.
  summary: ""
parameters:
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Indicates that this cmdlet runs the command as a background job.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Microsoft.Management.Infrastructure.CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a **New-CimSession** or **Get-CimSession** cmdlet.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: PSDesiredStateConfiguration.Restore-DscConfiguration
name: Restore-DscConfiguration
description: |-
  The **Restore-DscConfiguration** cmdlet reapplies the previous configuration for the node, if a previous configuration exists.
  Specify computers by using Common Information Model (CIM) sessions.
  If you do not specify a target computer, the cmdlet restores the configuration of the local computer.
  If there is no previous configuration for a particular node, this cmdlet returns an error message.

  This cmdlet does not support the **Confirm** parameter.
metadata:
  external help file: Restore-DSCConfiguration.cdxml-help.xml
  keywords: powershell,cmdlet
  Locale: en-US
  Module Name: PSDesiredStateConfiguration
  ms.date: 06/09/2017
  online version: https://docs.microsoft.com/powershell/module/psdesiredstateconfiguration/restore-dscconfiguration?view=powershell-5.1&WT.mc_id=ps-gethelp
  schema: 2.0.0
  title: Restore-DscConfiguration
