# Rule definitions live in .github

# Include a custom rule package
# customRules:
#   .github

# Fix any fixable errors
fix: all Microsoft

# Define a custom front matter pattern
# frontMatter: Goo()(\a\b|\a|\b|$)

# Define glob expressions to use (only valid at root)
# globs:
on: oneui_Experimental_features.md"

# Define glob expressions to mandatory
mandatory:
  + .vscode
  + assets
  + tests
  + tools

