name: "ðŸ› Report a documentation issue"
description: >-
  Report an issue with current documentation.
labels:
  - issue-doc-bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Use this template to report issues with documentation. This can include typos, technical and factual errors, grammar, spelling, formatting, presentation, etc.

        Support questions should be posted to community support forums. See the [Community support](https://learn.microsoft.com/powershell/scripting/community/community-support) page.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Existing Issue:** Search the existing issues for this repository. If there is an issue
            that fits your needs do not file a new one. Subscribe, react, or comment on that issue
            instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Typo in `Get-Foo` cmdlet" instead of "Typo."
          required: true
        - label: >-
            **Verify Version:** If there is a mismatch between documentation and the behavior on
            your system, ensure that the version you are using is the same as the documentation.
            Check this box if they match or the issue you are reporting is not version specific.
          required: true
  - type: textarea
    id: link_list
    validations:
      required: true
    attributes:
      label: Links
      description: >-
        Provide a list of links to the documentation page(s) that show the problem you are
        reporting. Use the markdown list syntax for each item. If you are linking to the source for the
        document, please use the permalink to the lines that show the problem. If you are linking to
        the live page for the document, please ensure each link is to the nearest header anchor to
        the problem instead of the page itself.
      placeholder: |
        - https://github.com/MicrosoftDocs/PowerShell-Docs-Modules/blob/2d7879a4c26b4a9d3aac906d18847f27ae509cdd/reference/docs-conceptual/Crescendo/overview.md?plain=1#L31-L38
        - https://learn.microsoft.com/powershell/utility-modules/crescendo/overview?view=ps-modules#crescendo-specific-terminology
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of the problem.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team update
        the documentation. Additional details may not be useful for typos, grammar, formatting, etc.
        For technical or factual errors, please include code snippets and output to show how the
        documentation is incorrect.
  - type: textarea
    id: suggestion
    validations:
      required: false
    attributes:
      label: Suggested Fix
      description: >-
        If you have an idea for how to fix the problem you're identifying, include it here.
