name: "🛠 Document a product change"
description: >-
  Request documentation for a new or updated feature, cmdlet, parameter, or behavior.
labels:
  - issue-doc-idea
  - needs-triage
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >-
        These steps are required. After you've completed each step, check the box for it before
        moving on.
      options:
        - label: >-
            **Existing Issue:** Search the existing issues for this repository. If there is an issue
            that fits your needs do not file a new one. Subscribe, react, or comment on that issue
            instead.
          required: true
        - label: >-
            **Descriptive Title:** Write the title for this issue as a short synopsis. If possible,
            provide context. For example, "Document new `Get-Foo` cmdlet" instead of "New cmdlet."
          required: true
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: >-
        Write a clear and concise description of change requiring documentation.
      placeholder: |
        Describe the impact of the change and high-level examples, if possible. Include any new or
        changed parameters and changed output. Put code and output inside code blocks. For example:

        ```powershell
        # Anything in this block is rendered as PowerShell code.
        Get-ChildItem -Path 'Some/Folder'
        ```

        ```text
        Anything in this block is rendered as mono-spaced plain text without highlighting.
        ```
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team write
        the documentation.
  - type: textarea
    id: file_list
    validations:
      required: false
    attributes:
      label: Articles
      description: >-
        Provide a list of files that need to be updated or created. If possible, include the path to
        the file relative to the repository's root folder. Use the markdown list syntax for each
        item. Cmdlet reference and about topics go in the `reference/x.y` folder for the appropriate
        version (e.g. `reference/7.3`). Other articles typically go in the
        `reference/docs-conceptual` folder.
      placeholder: |
        - reference/7.3/ModuleName
        - reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-73.md
  - type: textarea
    id: source_prs
    validations:
      required: true
    attributes:
      label: Related Source Pull Requests
      description: >-
        Provide the list of PRs in the source repository that are related to this requirement. Use
        the markdown list syntax for each item.
      placeholder: |
        - PowerShell/Powershell#1234567
  - type: textarea
    id: source_issues
    validations:
      required: true
    attributes:
      label: Related Source Issues
      description: >-
        Provide the list of issues in the source repository that are related to this requirement.
        Use the markdown list syntax for each item.
      placeholder: |
        - PowerShell/Powershell#1234567
