name: :page_facing_up: Feedback control template | Do not use
title: "[Documentation feedback] - "
description: >-
  This template is intended for use by the feedback control on the bottom of every page on the live
  site. If you aren't using the feedback control, choose one of the other templates.
labels:
  - "needs-triage"
body:
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: author
    validations:
      required: true
    attributes:
      label: Author
      description: GitHub Id of the author
  - type: input
    id: documentVersionIndependentId
    validations:
      required: true
    attributes:
      label: Document Id
      description: Version independent document Id
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: |
        Write a short description of the problem or feedback.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team update
        the documentation. Additional details may not be useful for typos, grammar, formatting, etc.
        For technical or factual errors, please include code snippets and output to show how the
        documentation is incorrect.
  - type: textarea
    id: environment
    validations:
      required: false
    attributes:
      label: Environment
      description: |
        Provide information about your environment. For example, copy the output from the following commands (as appropriate) to show the configuration of your environment.

        ```powershell
        $PSVersionTable
        Get-Module
        ```
      render: console
      placeholder: |
        PS> $PSVersionTable

        Name                           Value
        ----                           -----
        PSVersion                      7.4.0-preview.5
        PSEdition                      Core
        GitCommitId                    7.4.0-preview.5
        OS                             Microsoft Windows 10.0.22621
        Platform                       Win32NT
        PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
        PSRemotingProtocolVersion      2.3
        SerializationVersion           1.1.0.1
        WSManStackVersion              3.0

        PS> Get-Module

        ModuleType Version    PreRelease Name                                ExportedCommands
        ---------- -------    ---------- ----                                ----------------
        Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
        Binary     0.9.0      rc1        Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PS…
        Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
        Script     2.3.2      beta2      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
