# About topics have different line length requirements; their text is
# automatically wrapped at 80 characters, so it's preferable to control
# the wrapping here instead.
extends: ../../../../.markdownlint.yaml
MD013: # line-length
  code_block_line_length: 74
  code_blocks: true
  heading_line_length: 79
  headings: true
  line_length: 79
  stern: true
  tables: false
