name: Docker Image CI
(off)
php: on
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build: hub

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
